[advisories]
version = 2
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
]

[bans]
version = 2
multiple-versions = "warn"
wildcards = "deny"

[sources]
version = 2
unknown-registry = "deny"
unknown-git = "deny"